version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python ./src/main.py
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    volumes:
      - .:/src
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - default
    depends_on:
      - db

  db:
    container_name: pg_container
    image: postgres:12.12
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"