FROM ubuntu:22.10

ARG USERNAME=mwehby
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get -y update \
    && apt-get -y upgrade \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME

# Install python3
RUN sudo apt-get -y install python3 && sudo apt-get -y install python3-pip \
     && sudo apt-get -y install python3-venv
# Install basic tools
RUN sudo apt-get -y install vim && sudo apt-get -y install tree

# Install bat, an alternative to the cat command
RUN sudo apt-get -y install bat

# Clean up APT when done.
RUN sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Create directories to use for development
RUN cd ~  && mkdir py-api-dev && cd py-api-dev && mkdir src

WORKDIR /home/$USERNAME

# RUN sudo pip3 install --upgrade setuptools pip && pip3 install --user pipenv

RUN sudo echo 'alias python=python3' >> /home/$USERNAME/.bashrc
RUN sudo echo 'alias bat=batcat' >> /home/$USERNAME/.bashrc

CMD [ "/sbin/init" ]
